### ISSUE TITLE
Unable to load Banner page on web

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/GI-Weekly-Material-Tracker#606]
## Describe Bug Below
```
NoSuchMethodError: method not found: 'apply' on null
     at Object.cb (https://gi-weekly-material-tracker.web.app/main.dart.js:8342:23)
     at DA.abg (https://gi-weekly-material-tracker.web.app/main.dart.js:50858:10)
     at DA.Os (https://gi-weekly-material-tracker.web.app/main.dart.js:50859:21)
     at an2.$1 (https://gi-weekly-material-tracker.web.app/main.dart.js:50829:40)
     at xx.a2 (https://gi-weekly-material-tracker.web.app/main.dart.js:40628:20)
     at aaj.ae6 (https://gi-weekly-material-tracker.web.app/main.dart.js:50794:5)
     at aaj.oY (https://gi-weekly-material-tracker.web.app/main.dart.js:50796:30)
     at KN.QA (https://gi-weekly-material-tracker.web.app/main.dart.js:88923:7)
     at KN.Fz (https://gi-weekly-material-tracker.web.app/main.dart.js:88925:18)
     at KN.a8 (https://gi-weekly-material-tracker.web.app/main.dart.js:88903:6)
```

## What is the current version this bug is found at? Replace as needed
Version 2.2.2 build web.b9

## Steps to reproduce bug:
- Launch page
- Browse to Wish banners page

## Any other information/screenshots/videos
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/5357412/182025163-bf7175e1-b8c1-46a3-a5fd-1d06dab38306.png">

**Comment by itachi1706** [comment]
Issue might have been inadvertently fixed. We will confirm with the staging site @ https://github.com/itachi1706/GI-Weekly-Material-Tracker/deployments/activity_log?environment=Staging-Web

**Comment by itachi1706** [comment]
Seems like sometimes it works sometimes it doesn't. We will keep track of it further abit before closing if nothing happens
